### ISSUE TITLE
Connect-MSGraph should use Credential parameter instead of PSCredential

### ISSUE THREAD

**Issue by corbob** [microsoft/Intune-PowerShell-SDK#43]
It appears to be an accepted norm that credentials are passed in a parameter named Credential (of type PSCredential) Examples off the top of my head: ActiveDirectory Module, Web cmdlets, New-PSDrive, MSOnline, AzureAD.

A proposed "fix" would be to change the parameter to be named Credential, and add an alias for PSCredential to ensure backwards compatibility with any existing code using PSCredential

**Comment by rohitramu** [comment]
Thank you for the suggestion and for the PR!

Since the code in this repo is generated, we need to make changes in the "generator" repo.  If we make changes in this repo, they will get overwritten the next time we update it with the latest generated code.

I have made your change in the "generator" repo, so it will make it into the next version of the module: https://github.com/microsoftgraph/Intune-PowerShell-SDK-Code-Generator/commit/ee50de1b26888c1a98ecb068769d620a34ca9f46
